name: Deploy React App to Lightsail

on:
  push:
    branches:
      - main  # change if you use another branch


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy latest code on Lightsail
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USER }}
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          script: |
            echo "Navigating to app directory..."
            cd /home/ec2-user/TekBay

            echo "Pulling latest code..."
            git fetch origin main
            git reset --hard origin/main

            echo "Cleaning old local build..."
            rm -rf build

            echo "Installing dependencies..."
            npm ci

            echo "Building React app..."
            npm run build

            echo "Replacing old deployed build..."
            sudo rm -rf /usr/share/nginx/html/*
            sudo cp -r build/* /usr/share/nginx/html/

            echo "Restarting NGINX..."
            sudo systemctl restart nginx

            echo "Deployment complete!"

